#!/bin/bash

echo "force-unsafe-io" > /etc/dpkg/dpkg.cfg.d/02apt-speedup
echo "Acquire::http {No-Cache=True;};" > /etc/apt/apt.conf.d/no-cache
echo 'Acquire::Languages "none";' > /etc/apt/apt.conf.d/no-lang


