package cap

var (
	CAP_AUDIT_CONTROL    = "audit_control"
	CAP_AUDIT_WRITE      = "audit_write"
	CAP_BLOCK_SUSPEND    = "block_suspend"
	CAP_CHOWN            = "chown"
	CAP_DAC_OVERRIDE     = "dac_override"
	CAP_DAC_READ_SEARCH  = "dac_read_search"
	CAP_FOWNER           = "fowner"
	CAP_FSETID           = "fsetid"
	CAP_INIT_EFF_SET     = "init_eff_set"
	CAP_IPC_LOCK         = "ipc_lock"
	CAP_IPC_OWNER        = "ipc_owner"
	CAP_KILL             = "kill"
	CAP_LAST_CAP         = "last_cap"
	CAP_LEASE            = "lease"
	CAP_LINUX_IMMUTABLE  = "linux_immutable"
	CAP_MAC_ADMIN        = "mac_admin"
	CAP_MAC_OVERRIDE     = "mac_override"
	CAP_MKNOD            = "mknod"
	CAP_NET_ADMIN        = "net_admin"
	CAP_NET_BIND_SERVICE = "net_bind_service"
	CAP_NET_BROADCAST    = "net_broadcast"
	CAP_NET_RAW          = "net_raw"
	CAP_SETFCAP          = "setfcap"
	CAP_SETGID           = "setgid"
	CAP_SETPCAP          = "setpcap"
	CAP_SETUID           = "setuid"
	CAP_SYS_ADMIN        = "sys_admin"
	CAP_SYS_BOOT         = "sys_boot"
	CAP_SYS_CHROOT       = "sys_chroot"
	CAP_SYSLOG           = "syslog"
	CAP_SYS_MODULE       = "sys_module"
	CAP_SYS_NICE         = "sys_nice"
	CAP_SYS_PACCT        = "sys_pacct"
	CAP_SYS_PTRACE       = "sys_ptrace"
	CAP_SYS_RAWIO        = "sys_rawio"
	CAP_SYS_RESOURCE     = "sys_resource"
	CAP_SYS_TIME         = "sys_time"
	CAP_SYS_TTY_CONFIG   = "sys_tty_config"
	CAP_WAKE_ALARM       = "wake_alarm"
)
